name: Build KMG2D

on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Package KMG2D
    runs-on: windows-latest

    steps:
      # 1. Récupèrer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.8'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller winshell pywin32
          pip install -r requirements.txt

      # 4. Génèrer le fichier executable avec PyInstaller
      - name: Build executable
        run: |
          pyinstaller --onefile --windowed --name "KMG2D" --icon=icon.ico src/app.py

      # 5. Upload le setup en tant qu'artifact
      - name: Upload setup.exe
        uses: actions/upload-artifact@v4
        with:
          name: KMG2D
          path: src/dist/KMG2D.exe

      # 6. Créer une release si nécessaire
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: src/dist/KMG2D.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
